// Cognito Configuration - values provided by env.js (generated by CDK at deploy time)
const AWS_REGION = window.APP_CONFIG.AWS_REGION;
const USER_POOL_ID = window.APP_CONFIG.USER_POOL_ID;
const CLIENT_ID = window.APP_CONFIG.CLIENT_ID;
const COGNITO_DOMAIN = window.APP_CONFIG.COGNITO_DOMAIN;
const REDIRECT_URI = window.location.origin + '/';


// Helper function to show alerts
function showAuthAlert(message, type = 'info') {
  //console.log(`[${type.toUpperCase()}] ${message}`);
  // Try to use showAlert if it exists, otherwise just log
  if (typeof showAlert === 'function') {
    showAlert(message, type);
  } else {
    alert(message);
  }
}

// Get the authorization code from URL (after OAuth redirect)
function handleOAuthCallback() {
  const params = new URLSearchParams(window.location.search);
  const code = params.get('code');
  const error = params.get('error');
  
  //console.log('handleOAuthCallback called', { code, error });
  
  if (error) {
    console.error('OAuth error:', error);
    showAuthAlert(`Authentication error: ${error}`, 'danger');
    return;
  }
  
  if (code) {
    //console.log('Authorization code found, exchanging for token...');
    exchangeCodeForToken(code);
  }
}

// Exchange authorization code for token
async function exchangeCodeForToken(code) {
  const tokenUrl = `https://${COGNITO_DOMAIN}/oauth2/token`;
  
  //console.log('Exchanging code for token at:', tokenUrl);
  
  try {
    const response = await fetch(tokenUrl, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/x-www-form-urlencoded',
      },
      body: new URLSearchParams({
        grant_type: 'authorization_code',
        client_id: CLIENT_ID,
        code: code,
        redirect_uri: REDIRECT_URI,
      }),
    });
    
    const data = await response.json();
    
    /*console.log('Token response:', { 
      status: response.status, 
      ok: response.ok, 
      hasIdToken: !!data.id_token,
      error: data.error,
      errorDescription: data.error_description 
    });*/
    
    if (response.ok && data.id_token) {
      localStorage.setItem('idToken', data.id_token);
      localStorage.setItem('accessToken', data.access_token);
      if (data.refresh_token) {
        localStorage.setItem('refreshToken', data.refresh_token);
      }
      
      // Extract and store user info from the ID token
      try {
        const parts = data.id_token.split('.');
        if (parts.length === 3) {
          const tokenPayload = JSON.parse(atob(parts[1]));
          localStorage.setItem('userName', tokenPayload.name || tokenPayload.email || 'User');
          localStorage.setItem('userEmail', tokenPayload.email || '');
          localStorage.setItem('userPicture', tokenPayload.picture || '');
        }
      } catch (decodeError) {
        console.error('Error decoding token payload:', decodeError);
      }
      
      //console.log('User authenticated successfully!');
      // Clean up URL and redirect to home
      window.history.replaceState({}, document.title, window.location.pathname);
      updateAuthUI().catch(err => console.error('Error updating auth UI:', err));
      showAuthAlert('Successfully logged in!', 'success');
    } else {
      console.error('Token exchange failed:', data);
      showAuthAlert(`Login failed: ${data.error_description || 'Unknown error'}`, 'danger');
    }
  } catch (error) {
    console.error('Error exchanging code for token:', error);
    showAuthAlert('An error occurred during login. Please try again.', 'danger');
  }
}

// Login with Google
function loginWithGoogle() {
  const authUrl = `https://${COGNITO_DOMAIN}/oauth2/authorize?` +
    `client_id=${CLIENT_ID}&` +
    `response_type=code&` +
    `scope=openid+email+profile&` +
    `redirect_uri=${encodeURIComponent(REDIRECT_URI)}&` +
    `identity_provider=Google`;
  
  window.location.href = authUrl;
}

// Login with Cognito (email/password)
async function loginWithEmail(email, password) {
  try {
    const response = await fetch(`https://${COGNITO_DOMAIN}/oauth2/token`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/x-www-form-urlencoded',
      },
      body: new URLSearchParams({
        grant_type: 'password',
        client_id: CLIENT_ID,
        username: email,
        password: password,
        scope: 'openid email profile',
      }),
    });
    
    const data = await response.json();
    
    if (response.ok && data.id_token) {
      localStorage.setItem('idToken', data.id_token);
      localStorage.setItem('accessToken', data.access_token);
      if (data.refresh_token) {
        localStorage.setItem('refreshToken', data.refresh_token);
      }
      
      // Extract and store user info from the ID token
      try {
        const parts = data.id_token.split('.');
        if (parts.length === 3) {
          const tokenPayload = JSON.parse(atob(parts[1]));
          localStorage.setItem('userName', tokenPayload.name || tokenPayload.email || 'User');
          localStorage.setItem('userEmail', tokenPayload.email || '');
          localStorage.setItem('userPicture', tokenPayload.picture || '');
        }
      } catch (decodeError) {
        console.error('Error decoding token payload:', decodeError);
      }
      
      //console.log('User authenticated successfully!');
      updateAuthUI();
      showAuthAlert('Successfully logged in!', 'success');
      return true;
    } else {
      console.error('Login failed:', data);
      showAuthAlert('Login failed. Check your email and password.', 'danger');
      return false;
    }
  } catch (error) {
    console.error('Error during login:', error);
    showAuthAlert('An error occurred during login. Please try again.', 'danger');
    return false;
  }
}

// Logout
function logout() {
  // Clear all auth-related data
  localStorage.removeItem('idToken');
  localStorage.removeItem('accessToken');
  localStorage.removeItem('refreshToken');
  localStorage.removeItem('userName');
  localStorage.removeItem('userEmail');
  localStorage.removeItem('userPicture');
  
  const logoutUrl = `https://${COGNITO_DOMAIN}/logout?` +
    `client_id=${CLIENT_ID}&` +
    `logout_uri=${encodeURIComponent(REDIRECT_URI)}`;
  
  updateAuthUI();
  showAuthAlert('You have been logged out.', 'success');
  window.location.href = logoutUrl;
}

// Refresh token when it expires
async function refreshAccessToken() {
  const refreshToken = localStorage.getItem('refreshToken');
  if (!refreshToken) {
    console.warn('No refresh token available, forcing logout');
    logout();
    return false;
  }

  try {
    const response = await fetch(`https://${COGNITO_DOMAIN}/oauth2/token`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/x-www-form-urlencoded',
      },
      body: new URLSearchParams({
        grant_type: 'refresh_token',
        client_id: CLIENT_ID,
        refresh_token: refreshToken,
      }),
    });

    const data = await response.json();
    if (response.ok && data.id_token) {
      console.log('🔄 Token refreshed successfully at', new Date().toLocaleTimeString());
      localStorage.setItem('idToken', data.id_token);
      localStorage.setItem('accessToken', data.access_token);
      // Refresh_token may also be rotated, update if provided
      if (data.refresh_token) {
        localStorage.setItem('refreshToken', data.refresh_token);
      }
      
      // Update user info from new token to keep it in sync
      try {
        const parts = data.id_token.split('.');
        if (parts.length === 3) {
          const tokenPayload = JSON.parse(atob(parts[1]));
          localStorage.setItem('userName', tokenPayload.name || tokenPayload.email || 'User');
          localStorage.setItem('userEmail', tokenPayload.email || '');
          localStorage.setItem('userPicture', tokenPayload.picture || '');
        }
      } catch (decodeError) {
        console.error('Error decoding refreshed token payload:', decodeError);
      }
      
      return true;
    } else {
      console.error('Token refresh failed:', data);
      logout();
      return false;
    }
  } catch (error) {
    console.error('Error refreshing token:', error);
    logout();
    return false;
  }
}

// Check if user is authenticated
function isAuthenticated() {
  return localStorage.getItem('idToken') !== null;
}

// Get user info from ID token
async function getUserInfo() {
  // First, try to return cached user info from localStorage
  const cachedEmail = localStorage.getItem('userEmail');
  const cachedName = localStorage.getItem('userName');
  const cachedPicture = localStorage.getItem('userPicture');
  
  if (cachedEmail) {
    // We have cached info, but still validate the token
    const idToken = localStorage.getItem('idToken');
    if (!idToken) return null;

    try {
      const parts = idToken.split('.');
      if (parts.length !== 3) {
        // Invalid token format, try to refresh
        const recovered = await refreshAccessToken();
        if (recovered) {
          return await getUserInfo();
        }
        return null;
      }

      const payload = JSON.parse(atob(parts[1]));

      // Check if token has expired
      if (payload.exp && payload.exp * 1000 < Date.now()) {
        console.warn('⏰ Token expired!', 'Expired at:', new Date(payload.exp * 1000).toLocaleTimeString(), 'Now:', new Date().toLocaleTimeString());
        // Token expired, try to refresh
        const recovered = await refreshAccessToken();
        if (recovered) {
          return await getUserInfo();
        }
        return null;
      }

      // Token is valid, return cached user info
      return {
        email: cachedEmail,
        name: cachedName || 'User',
        picture: cachedPicture,
        sub: payload.sub,
      };
    } catch (error) {
      console.error('Error validating token:', error);
      // Try to recover with refresh
      const recovered = await refreshAccessToken();
      if (recovered) {
        return await getUserInfo();
      }
      return null;
    }
  }

  // No cached email, try to decode token directly
  const idToken = localStorage.getItem('idToken');
  if (!idToken) return null;

  try {
    const parts = idToken.split('.');
    if (parts.length !== 3) {
      console.warn('Invalid token format detected, attempting recovery...');
      const recovered = await refreshAccessToken();
      if (recovered) {
        console.log('✅ Token recovered, retrying getUserInfo...');
        return await getUserInfo();
      }
      return null;
    }

    const payload = JSON.parse(atob(parts[1]));

    if (payload.exp && payload.exp * 1000 < Date.now()) {
      console.warn('Token has expired, attempting recovery...');
      const recovered = await refreshAccessToken();
      if (recovered) {
        console.log('✅ Token recovered, retrying getUserInfo...');
        return await getUserInfo();
      }
      return null;
    }

    // Cache the user info for future use
    const userObj = {
      email: payload.email || payload['cognito:username'],
      name: payload.name || payload.given_name || 'User',
      picture: payload.picture,
      sub: payload.sub,
    };
    
    localStorage.setItem('userEmail', userObj.email);
    localStorage.setItem('userName', userObj.name);
    localStorage.setItem('userPicture', userObj.picture || '');
    
    return userObj;
  } catch (error) {
    console.error('Error decoding token, attempting recovery...', error);
    const recovered = await refreshAccessToken();
    if (recovered) {
      console.log('✅ Token recovered, retrying getUserInfo...');
      return await getUserInfo();
    }
    return null;
  }
}

// Update UI based on auth status
async function updateAuthUI() {
  //login, logout, etc. is handled in the avatar menu
  const accountMenuDropdown = document.getElementById('accountMenuDropdown');
  
  // Only update if the element exists (not all pages have this)
  if (!accountMenuDropdown) return;
  
  // Clear existing items in the avatar menu
  accountMenuDropdown.innerHTML = '';  

  //settings are there regardless of auth state
  const newItem0 = document.createElement('sl-menu-item');
  const settingsIcon = document.createElement('sl-icon');
  settingsIcon.setAttribute('slot', 'prefix');
  settingsIcon.setAttribute('name', 'gear');
  newItem0.appendChild(settingsIcon);
  newItem0.appendChild(document.createTextNode('Settings'));
  accountMenuDropdown.appendChild(newItem0);

  //add <sl-divider>
  const divider = document.createElement('sl-divider');
  accountMenuDropdown.appendChild(divider);

  //if authenticated, update avatar, show my bookmarks, my uploads, and logout options

  if (isAuthenticated()) {
    const user = await getUserInfo();
    //menu items for logged in user
    const uploadLink = document.getElementById("uploadLink");
    if (uploadLink) uploadLink.style.display = "block";
    
    if (user) {
      const displayName = user.name || user.email || 'User';
      const avatarTooltip = document.getElementById("avatarTooltip");
      if (avatarTooltip) avatarTooltip.setAttribute("content", displayName);

      // Update avatar sl component if exists
      const userAvatar = document.getElementById('userAvatar');
      if (userAvatar) {
        if (user.picture) {
          userAvatar.setAttribute('image', user.picture);
        } else if (user.name) {
          userAvatar.setAttribute('label', user.name);
        } else {
          userAvatar.setAttribute('label', 'User');
        }
      }

      //add my bookmarks
      const newItem1 = document.createElement('sl-menu-item');
      const bookmarkIcon = document.createElement('sl-icon');
      bookmarkIcon.setAttribute('slot', 'prefix');
      bookmarkIcon.setAttribute('name', 'bookmark');
      newItem1.appendChild(bookmarkIcon);
      newItem1.appendChild(document.createTextNode('My Bookmarks'));
      accountMenuDropdown.appendChild(newItem1);
      //add my uploads  

      const newItem2 = document.createElement('sl-menu-item');
      const uploadIcon = document.createElement('sl-icon');
      uploadIcon.setAttribute('slot', 'prefix');
      uploadIcon.setAttribute('name', 'upload');
      newItem2.appendChild(uploadIcon);
      newItem2.appendChild(document.createTextNode('My Uploads'));
      accountMenuDropdown.appendChild(newItem2);
        //add <sl-divider>
      const divider = document.createElement('sl-divider');
      accountMenuDropdown.appendChild(divider);
      //add logout
      const newItem3 = document.createElement('sl-menu-item');
      const logoutIcon = document.createElement('sl-icon');
      logoutIcon.setAttribute('slot', 'prefix');
      logoutIcon.setAttribute('name', 'box-arrow-right');
      newItem3.appendChild(logoutIcon);
      newItem3.appendChild(document.createTextNode('Logout'));
      accountMenuDropdown.appendChild(newItem3);      
    } 
  } else {
    //not logged in
    const newItem = document.createElement('sl-menu-item');
    const loginIcon = document.createElement('sl-icon');
    loginIcon.setAttribute('slot', 'prefix');
    loginIcon.setAttribute('name', 'box-arrow-in-right');
    newItem.appendChild(loginIcon);
    newItem.appendChild(document.createTextNode('Login'));
    accountMenuDropdown.appendChild(newItem);
  }

}

// Initialize auth on page load
window.addEventListener('DOMContentLoaded', function() {
  handleOAuthCallback();
  updateAuthUI().catch(err => console.error('Error updating auth UI:', err));
});


// Also handle on load event
window.addEventListener('load', function() {
  // Make sure auth UI is updated
  updateAuthUI().catch(err => console.error('Error updating auth UI:', err));
});

